# Eigenvectors

## Definition

A non-zero vector v is an eigenvector of A if:

A v = λ v

where:

λ = eigenvalue  
v ≠ 0  

Eigenvectors represent directions that remain unchanged under transformation by A.

---

## Important

1. Eigenvectors correspond to eigenvalues.
2. Each eigenvalue may have one or more eigenvectors.
3. Eigenvectors are defined up to scalar multiplication.


In [1]:
import numpy as np

# ---------------------------------------------------
# Example 1: Compute eigenvectors
# ---------------------------------------------------

A = np.array([[2, 1],
              [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)


# ---------------------------------------------------
# Example 2: Verify A v = λ v
# ---------------------------------------------------

# Take first eigenvalue and eigenvector
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0]

left = A @ v_1
right = lambda_1 * v_1

print("\nA @ v:")
print(left)

print("\nλ v:")
print(right)


# ---------------------------------------------------
# Example 3: Larger matrix
# ---------------------------------------------------

B = np.array([[4, 2],
              [1, 3]])

eigvals_B, eigvecs_B = np.linalg.eig(B)

print("\nMatrix B:\n", B)
print("Eigenvalues of B:\n", eigvals_B)
print("Eigenvectors of B:\n", eigvecs_B)


Matrix A:
 [[2 1]
 [1 2]]

Eigenvalues:
 [3. 1.]

Eigenvectors (columns):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

A @ v:
[2.12132034 2.12132034]

λ v:
[2.12132034 2.12132034]

Matrix B:
 [[4 2]
 [1 3]]
Eigenvalues of B:
 [5. 2.]
Eigenvectors of B:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
