# Scalar Multiplication

## Definition

Scalar multiplication multiplies every element of a matrix by a scalar value.

If:

A ∈ R^(m × n)  
λ ∈ R (scalar)

Then:

B = λA

where:

B[i,j] = λ · A[i,j]

---

## Properties

1. Distributive over matrix addition  
   λ(A + B) = λA + λB

2. Distributive over scalar addition  
   (λ + μ)A = λA + μA

3. Associative  
   λ(μA) = (λμ)A

4. Identity scalar  
   1A = A

5. Zero scalar  
   0A = 0


In [1]:
import numpy as np

# Example 1: Basic scalar multiplication
A = np.array([[1, 2],
              [3, 4]])

scalar = 3

B = scalar * A  # multiply every element by scalar

print("3A:\n", B)


# Example 2: Negative scalar
negative_scalar = -2

C = negative_scalar * A

print("\n-2A:\n", C)


# Example 3: Float scalar
float_scalar = 0.5

D = float_scalar * A

print("\n0.5A:\n", D)


# Example 4: Verify distributive property
X = np.array([[1, 1],
              [1, 1]])

left_side = 2 * (A + X)
right_side = 2 * A + 2 * X

print("\n2(A + X):\n", left_side)
print("\n2A + 2X:\n", right_side)


# Example 5: Using explicit NumPy multiplication
E = np.multiply(5, A)

print("\nUsing np.multiply(5, A):\n", E)


3A:
 [[ 3  6]
 [ 9 12]]

-2A:
 [[-2 -4]
 [-6 -8]]

0.5A:
 [[0.5 1. ]
 [1.5 2. ]]

2(A + X):
 [[ 4  6]
 [ 8 10]]

2A + 2X:
 [[ 4  6]
 [ 8 10]]

Using np.multiply(5, A):
 [[ 5 10]
 [15 20]]
