# Element-wise Multiplication (Hadamard Product)

## Definition

Element-wise multiplication multiplies corresponding elements of two matrices.

If:

A, B ∈ R^(m × n)

Then:

C = A ⊙ B

where:

C[i,j] = A[i,j] · B[i,j]

This is also called the Hadamard Product.

---

## Condition

shape(A) = shape(B)

If shapes differ → operation is undefined.

---

## Important

Element-wise multiplication is NOT matrix multiplication.

Matrix multiplication uses dot products.  
Element-wise multiplication multiplies entries directly.

---

## Properties

1. Commutative  
   A ⊙ B = B ⊙ A

2. Associative  
   (A ⊙ B) ⊙ C = A ⊙ (B ⊙ C)

3. Distributive over addition  
   A ⊙ (B + C) = A ⊙ B + A ⊙ C


In [1]:
import numpy as np

# Example 1: Basic 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise multiplication using *
C = A * B

print("A * B:\n", C)


# Example 2: Using np.multiply()
D = np.multiply(A, B)

print("\nUsing np.multiply():\n", D)


# Example 3: 3x3 matrices
X = np.array([[1, 0, 2],
              [-1, 3, 1],
              [3, 2, 0]])

Y = np.array([[0, 3, -1],
              [2, 1, 4],
              [1, 0, 5]])

Z = X * Y

print("\nX * Y:\n", Z)


# Example 4: Verify distributive property
left = A * (B + A)
right = A * B + A * A

print("\nA ⊙ (B + A):\n", left)
print("\nA ⊙ B + A ⊙ A:\n", right)


# Example 5: Shape mismatch error
M = np.array([[1, 2],
              [3, 4]])

N = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    result = M * N
except ValueError as e:
    print("\nError:", e)


A * B:
 [[ 5 12]
 [21 32]]

Using np.multiply():
 [[ 5 12]
 [21 32]]

X * Y:
 [[ 0  0 -2]
 [-2  3  4]
 [ 3  0  0]]

A ⊙ (B + A):
 [[ 6 16]
 [30 48]]

A ⊙ B + A ⊙ A:
 [[ 6 16]
 [30 48]]

Error: operands could not be broadcast together with shapes (2,2) (2,3) 
