# Matrix Multiplication

## Definition

Matrix multiplication is defined using row–column dot products.

If:

A ∈ R^(m × n)  
B ∈ R^(n × p)

Then:

C = AB

where:

C[i,j] = Σ ( A[i,k] · B[k,j] )

The result has shape:

(m × p)

---

## Condition

Number of columns in A = Number of rows in B

(n must match)

---

## Important

Matrix multiplication is NOT element-wise multiplication.

A * B  → Hadamard product  
A @ B  → Matrix multiplication

---

## Properties

1. Not commutative  
   AB ≠ BA

2. Associative  
   (AB)C = A(BC)

3. Distributive  
   A(B + C) = AB + AC


In [1]:
import numpy as np

# Example 1: 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using @
C = A @ B

print("A @ B:\n", C)


# Example 2: Using np.dot()
D = np.dot(A, B)

print("\nUsing np.dot():\n", D)


# Example 3: Non-square matrices (2x3) @ (3x2)
X = np.array([[1, 2, 3],
              [4, 5, 6]])

Y = np.array([[7, 8],
              [9, 10],
              [11, 12]])

Z = X @ Y

print("\nX @ Y:\n", Z)


# Example 4: Show non-commutativity
print("\nA @ B:\n", A @ B)
print("\nB @ A:\n", B @ A)


# Example 5: Shape mismatch error
M = np.array([[1, 2],
              [3, 4]])

N = np.array([[1, 2, 3],
              [4, 5, 6]])

try:
    result = M @ N
except ValueError as e:
    print("\nError:", e)


A @ B:
 [[19 22]
 [43 50]]

Using np.dot():
 [[19 22]
 [43 50]]

X @ Y:
 [[ 58  64]
 [139 154]]

A @ B:
 [[19 22]
 [43 50]]

B @ A:
 [[23 34]
 [31 46]]
