# Determinant

## Definition

The determinant is a scalar value associated with a square matrix.

If:

A ∈ R^(n × n)

Then:

det(A) ∈ R

For a 2×2 matrix:

A = | a  b |
    | c  d |

det(A) = ad − bc

The determinant measures how a linear transformation scales area (2D) or volume (3D).

If:

det(A) = 0  →  matrix is singular (not invertible)  
det(A) ≠ 0  →  matrix is invertible

---

## Geometric Meaning

|det(A)|  = scaling factor of area/volume  
sign(det(A)) = orientation (flip or not)

---

## Important Properties

1. det(I) = 1

2. det(AB) = det(A) det(B)

3. det(A^T) = det(A)

4. If a row (or column) is zero → det(A) = 0

5. If two rows are identical → det(A) = 0


In [1]:
import numpy as np

# ---------------------------------------------------
# Example 1: Determinant of 2x2 matrix (manual check)
# ---------------------------------------------------

A = np.array([[2, 3],
              [4, 5]])

# Using NumPy
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("\nDeterminant of A (NumPy):", det_A)

# Manual verification for 2x2:
# det(A) = (2*5 - 3*4) = 10 - 12 = -2
print("\nManual calculation (2*5 - 3*4):", 2*5 - 3*4)


# ---------------------------------------------------
# Example 2: Determinant of 3x3 matrix
# ---------------------------------------------------

B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

det_B = np.linalg.det(B)

print("\nMatrix B:\n", B)
print("\nDeterminant of B:", det_B)


# ---------------------------------------------------
# Example 3: Determinant of Identity matrix
# ---------------------------------------------------

I = np.eye(3)

print("\nIdentity Matrix:\n", I)
print("det(I):", np.linalg.det(I))


# ---------------------------------------------------
# Example 4: Singular matrix (determinant = 0)
# ---------------------------------------------------

# Second row is a multiple of first row
C = np.array([[1, 2],
              [2, 4]])

print("\nMatrix C:\n", C)
print("det(C):", np.linalg.det(C))


# ---------------------------------------------------
# Example 5: Property det(AB) = det(A) * det(B)
# ---------------------------------------------------

X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

left = np.linalg.det(X @ Y)
right = np.linalg.det(X) * np.linalg.det(Y)

print("\ndet(X @ Y):", left)
print("det(X) * det(Y):", right)


# ---------------------------------------------------
# Example 6: Property det(A^T) = det(A)
# ---------------------------------------------------

print("\ndet(A):", np.linalg.det(A))
print("det(A^T):", np.linalg.det(A.T))


Matrix A:
 [[2 3]
 [4 5]]

Determinant of A (NumPy): -2.0

Manual calculation (2*5 - 3*4): -2

Matrix B:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of B: 0.9999999999999964

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det(I): 1.0

Matrix C:
 [[1 2]
 [2 4]]
det(C): 0.0

det(X @ Y): 4.000000000000008
det(X) * det(Y): 4.000000000000011

det(A): -2.0
det(A^T): -2.000000000000001
