# Inverse of a Matrix

## Definition

The inverse of a square matrix A is a matrix A⁻¹ such that:

A A⁻¹ = I  
A⁻¹ A = I

where I is the identity matrix.

---

## Condition for Existence

A matrix is invertible (non-singular) if and only if:

det(A) ≠ 0

If:

det(A) = 0  →  A has no inverse.

Only square matrices can have an inverse.

---

## Important Idea

Inverse represents reversing a linear transformation.

If A transforms space,
A⁻¹ brings it back to original space.

---

## Numerical Stability Note

In practical machine learning:

Avoid computing inverse directly.

Instead of:

A_inv = np.linalg.inv(A)
x = A_inv @ b

Use:

x = np.linalg.solve(A, b)

`solve()` is:
- Faster
- More numerically stable
- More accurate


In [1]:
import numpy as np

# ---------------------------------------------------
# Example 1: Basic 2x2 matrix inverse
# ---------------------------------------------------

A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("\nInverse of A:\n", A_inv)

# Verify A * A_inv = Identity
print("\nA @ A_inv:\n", A @ A_inv)


# ---------------------------------------------------
# Example 2: 3x3 matrix inverse
# ---------------------------------------------------

B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

B_inv = np.linalg.inv(B)

print("\nMatrix B:\n", B)
print("\nInverse of B:\n", B_inv)

# Check identity
print("\nB @ B_inv:\n", B @ B_inv)


# ---------------------------------------------------
# Example 3: Singular matrix (no inverse)
# ---------------------------------------------------

C = np.array([[1, 2],
              [2, 4]])  # second row is multiple of first

print("\nMatrix C:\n", C)

try:
    C_inv = np.linalg.inv(C)
except np.linalg.LinAlgError as e:
    print("Error:", e)


# ---------------------------------------------------
# Example 4: Why solve() is better than inverse
# ---------------------------------------------------

A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

# Method 1: Using inverse (not recommended)
x1 = np.linalg.inv(A) @ b

# Method 2: Using solve (recommended)
x2 = np.linalg.solve(A, b)

print("\nSolution using inverse:", x1)
print("Solution using solve():", x2)


Matrix A:
 [[4 7]
 [2 6]]

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

A @ A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

Matrix B:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of B:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

B @ B_inv:
 [[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]

Matrix C:
 [[1 2]
 [2 4]]
Error: Singular matrix

Solution using inverse: [2. 3.]
Solution using solve(): [2. 3.]
