# Row Echelon Form (REF)

## Definition

A matrix is in Row Echelon Form if:

1. All zero rows are at bottom.
2. First non-zero entry in each row (pivot) is to the right of the one above.
3. Entries below pivots are zero.

Row operations used:

1. Swap rows
2. Multiply row by non-zero scalar
3. Add multiple of one row to another

REF is obtained using Gaussian elimination.


In [1]:
import numpy as np

def row_echelon_form(A):
    A = A.astype(float)
    rows, cols = A.shape
    pivot_row = 0

    for col in range(cols):
        if pivot_row >= rows:
            break

        # Find pivot
        max_row = np.argmax(abs(A[pivot_row:, col])) + pivot_row

        if A[max_row, col] == 0:
            continue

        # Swap rows
        A[[pivot_row, max_row]] = A[[max_row, pivot_row]]

        # Normalize pivot row
        A[pivot_row] = A[pivot_row] / A[pivot_row, col]

        # Eliminate below
        for r in range(pivot_row + 1, rows):
            A[r] = A[r] - A[r, col] * A[pivot_row]

        pivot_row += 1

    return A


# Example
A = np.array([[1, 2, 1],
              [2, 4, 0],
              [3, 6, 3]])

ref = row_echelon_form(A)

print("Row Echelon Form:\n", ref)


Row Echelon Form:
 [[ 1.  2.  1.]
 [-0. -0.  1.]
 [ 0.  0.  0.]]
