# Rank of a Matrix

## Definition

The rank of a matrix is the number of linearly independent rows (or columns).

Equivalent definition:

Rank = number of pivot positions in row echelon form.

---

## Properties

1. rank(A) ≤ min(m, n)
2. If rank(A) = n (square matrix), A is full rank
3. If rank(A) < n, matrix is rank deficient

Rank determines number of solutions of Ax = b.


In [2]:
import numpy as np

# ---------------------------------------------------
# Example 1: Full rank matrix
# ---------------------------------------------------

A = np.array([[1, 2],
              [3, 4]])

rank_A = np.linalg.matrix_rank(A)

print("Matrix A:\n", A)
print("Rank of A:", rank_A)


# ---------------------------------------------------
# Example 2: Rank deficient matrix
# ---------------------------------------------------

B = np.array([[1, 2],
              [2, 4]])   # second row is multiple of first

rank_B = np.linalg.matrix_rank(B)

print("\nMatrix B:\n", B)
print("Rank of B:", rank_B)


# ---------------------------------------------------
# Example 3: Larger matrix
# ---------------------------------------------------

C = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 1, 1]])

rank_C = np.linalg.matrix_rank(C)

print("\nMatrix C:\n", C)
print("Rank of C:", rank_C)


Matrix A:
 [[1 2]
 [3 4]]
Rank of A: 2

Matrix B:
 [[1 2]
 [2 4]]
Rank of B: 1

Matrix C:
 [[1 2 3]
 [2 4 6]
 [1 1 1]]
Rank of C: 2
